### ISSUE TITLE
keyboardInput cannot support 

### ISSUE THREAD

**Issue by gieghia** [simon-void/pikaday_datepicker_angular#2]
pikaday have keyboardInput option
 may be this angular library pikaday not have.

**Comment by simon-void** [comment]
indeed, i checked. There is no keyboardInput option in the Dart wrapper lib. You can check its
[PikadayOptions API](https://www.dartdocs.org/documentation/pikaday/1.2.0%2B1/lib.pikaday/PikadayOptions-class.html). I support most of the options present (though currently not the Callbacks).
